# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
  pre_tasks:
  - name: pre-run | update package cache
    tags: always
    apt: update_cache=yes
    changed_when: False
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: pre-run | install ansible requirements
    shell: >
      ansible-galaxy install -r requirements.yml

# run roles
- hosts: localhost
  connection: local
  tasks:
  - name: set roles
    set_fact:
      roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
    tags: always

  - name: run roles
    include_role:
      apply:
        tags:
        - "{{ roles_item }}"
      name: "{{ roles_item }}"
    loop_control:
      loop_var: roles_item
    with_items: "{{ roles }}"
    tags:
    - always

# end of run cleanup and reporting
- hosts: localhost
  become: true
  tasks:
  - name: cleanup package cache
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: autoremove orphan packages
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]