---
- name: download kubectl
  shell: >
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  warn: false

- name: install kubectl
  shell: >
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  become: yes

# - name: adding apt repository for Kubernetes
#   apt_repository:
#     repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
#     state: present
#     filename: kubernetes.list

# - name: install Kubernetes binaries
#   ansible.builtin.package:
#     name:
#     - kubectl
#   become: yes

- name: config folder
  ansible.builtin.file:
    mode: 0755
    path: "{{ ansible_user_dir }}/.kube/conf.d"
    state: directory

- name: copy configs
  copy:
    dest: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_item.key }}.conf"
    content: "{{ kubectl_config_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: kubectl_config_item
  with_items: "{{ kubectl_config | default({}) | dict2items }}"

- name: set active
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.kube/config"
    src: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_active }}.conf"
    state: link
  no_log: true
  when: kubectl_config[kubectl_config_active] is defined