---
- name: add ansible user
  user:
    name: autoprovisioner
    system: yes
  become: yes

- name: set up sudo for ansible user
  copy:
    src: files/sudoer_autoprovisioner
    dest: /etc/sudoers.d/autoprovisioner
    owner: root
    group: root
    mode: 0440
  become: yes

- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: autoprovisioner
    minute: "*/10"
    job: ansible-pull -o -U https://github.com/dichioniccolo/ansible-wsl.git
  become: yes