---
- name: download installer
  get_url:
    dest: /tmp/install-doppler.sh
    mode: 0755
    url: https://cli.doppler.com/install.sh

- name: install
  shell: /tmp/install-doppler.sh
  become: yes

- name: remove install
  file:
    path: /tmp/install-doppler.sh
    state: absent